# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

# Build Configuration
builds:
  - binary: '{{ .ProjectName }}_v{{ .Version }}'
    env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    goos:
      #- darwin
      #- freebsd
      - linux
      #- windows
    goarch:
      #- '386'
      - amd64
      #- arm
      #- arm64
    ignore:
      - goarch: arm
        goos: windows
      - goarch: arm64
        goos: freebsd
      - goarch: arm64
        goos: windows
    ldflags:
      - -s -w -X internal/provider.Version={{.Version}}

# Archive Arctefacts
archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

# Check Sum
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
  extra_files:
    - glob: 'terraform-registry-manifest.json'
      name_template: '{{ .ProjectName }}_{{ .Version }}_manifest.json'

# Sign Artefacts
signs:
  - artifacts: checksum
    args:
    - "--batch"
    - "--local-user"
    - "{{ .Env.GPG_FINGERPRINT }}"
    - "--output"
    - "${signature}"
    - "--detach-sign"
    - "${artifact}"

# Release Arctfacts
release:
  disable: false
  github:
    owner: kube-cloud
    name: terraform-provider-vsphere
  extra_files:
    - glob: 'terraform-registry-manifest.json'
      name_template: '{{ .ProjectName }}_{{ .Version }}_manifest.json'
  ids:
    - GPG_FINGERPRINT
  draft: false
