# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # Prepare release Note Stage
  release-notes:

    # Ubuntu Agent
    runs-on: ubuntu-latest

    # Stage Steps
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Generate Release Notes
        run: sed -n -e "1{/# /d;}" -e "2{/^$/d;}" -e "/# $(git describe --abbrev=0 --exclude="$(git describe --abbrev=0 --match='v*.*.*' --tags)" --match='v*.*.*' --tags | tr -d v)/q;p" CHANGELOG.md > release-notes.txt
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3.1.3
        with:
          name: release-notes
          path: release-notes.txt
          retention-days: 1
      - name: Print Branch/Tag Name
        run: echo "Current Branch/Tag Reference = ${{ github.ref }}"
  
  # Perform Release terraform Provider Stage
  terraform-provider-release:
    name: 'Terraform Provider Release'
    needs: [release-notes]
    uses: hashicorp/ghaction-terraform-provider-release/.github/workflows/community.yml@v2
    secrets:
      gpg-private-key: '${{ secrets.GPG_PRIVATE_KEY }}'
      gpg-private-key-passphrase: ${{ secrets.PASSPHRASE }}
    with:
      setup-go-version: 1.21.4
      release-notes: true
      product-version: '${{ github.ref }}'
      
