# This GitHub action can publish assets for release when a tag is created.
# Currently its setup to run on any tag that matches the pattern "v*" (ie. v0.1.0).
#
# This uses an action (paultyng/ghaction-import-gpg) that assumes you set your 
# private key in the `GPG_PRIVATE_KEY` secret and passphrase in the `PASSPHRASE`
# secret. If you would rather own your own GPG handling, please fork this action
# or use an alternative one for key handling.
#
# You will need to pass the `--batch` flag to `gpg` in your signing step 
# in `goreleaser` to indicate this is being used in a non-interactive mode.
#
name: Release
on:
  push:
    tags:
      - 'v*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # Prepare release Note Stage
  release-notes:

    # Ubuntu Agent
    runs-on: ubuntu-latest

    # Stage Steps
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Generate Release Notes
        run: sed -n -e "1{/# /d;}" -e "2{/^$/d;}" -e "/# $(git describe --abbrev=0 --exclude="$(git describe --abbrev=0 --match='v*.*.*' --tags)" --match='v*.*.*' --tags | tr -d v)/q;p" CHANGELOG.md > release-notes.txt
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3.1.3
        with:
          name: release-notes
          path: release-notes.txt
          retention-days: 1
      - name: Print Branch/Tag Name
        run: echo "Current Branch/Tag Reference = ${{ github.ref }}"

  # Perform Release terraform Provider Stage
  terraform-provider-release:
    name: 'Terraform Provider Release'
    needs: [release-notes]
    uses: hashicorp/ghaction-terraform-provider-release/.github/workflows/hashicorp.yml@v2
    secrets:
      gpg-private-key: '${{ secrets.GPG_PRIVATE_KEY }}'
      gpg-private-key-passphrase: ${{ secrets.PASSPHRASE }}
    with:
      setup-go-version: 1.21.4
      release-notes: true
      product-version: '${{ github.ref_name }}'
